server:
  port: 8080

spring:
  redis:
    host: dearlavion-redis
    port: 6379
    timeout: 5000ms

  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 65536

      routes:

        # ======================
        # Auth Service
        # ======================
        - id: auth-service
          uri: "http://dearlavion-authentication-service:${auth_port}"
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userOrIpKeyResolverBean}"
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 2

        # ======================
        # Core Service
        # ======================
        - id: core-service
          uri: "http://dearlavion-core-service:${core_port}"
          predicates:
            - Path=/api/core/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userOrIpKeyResolverBean}"
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 2

        # ======================
        # Notification Service (WebSocket)
        # ======================
        - id: notification-service
          uri: "http://dearlavion-notification-service:${notification_port}"
          predicates:
            - Path=/api/notification/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        # ======================
        # Kafka UI (AKHQ)
        # ======================
        - id: akhq
          uri: "http://dearlavion-akhq:${akhq_port}"
          predicates:
            - Path=/api/kafka/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Forwarded-Prefix, /api/kafka
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG